In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

In [5]:
data=pd.read_csv("/content/WineQT.csv")

In [6]:
data

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,1
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,2
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,3
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1594
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597

In [36]:
print(data['quality'].value_counts())

quality
5    483
6    462
7    143
4     33
8     16
3      6
Name: count, dtype: int64

In [8]:
data.sample()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
1131,6.1,0.715,0.1,2.6,0.053,13.0,27.0,0.99362,3.57,0.5,11.9,5,1582

In [41]:
# Good wine = quality >= 7
data['quality_label'] = (data['quality'] >= 7).astype(int)
print(data["quality_label"].value_counts())

quality_label
0    984
1    159
Name: count, dtype: int64

In [9]:
data[['fixed acidity','volatile acidity','citric acid','residual sugar','chlorides','free sulfur dioxide','density','pH','sulphates','alcohol','total sulfur dioxide','quality']].corr()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,density,pH,sulphates,alcohol,total sulfur dioxide,quality
fixed acidity,1.000000,-0.250728,0.673157,0.171831,0.107889,-0.164831,0.681501,-0.685163,0.174592,-0.075055,-0.110628,0.121970
volatile acidity,-0.250728,1.000000,-0.544187,-0.005751,0.056336,-0.001962,0.016512,0.221492,-0.276079,-0.203909,0.077748,-0.407394
citric acid,0.673157,-0.544187,1.000000,0.175815,0.245312,-0.057589,0.375243,-0.546339,0.331232,0.106250,0.036871,0.240821
residual sugar,0.171831,-0.005751,0.175815,1.000000,0.070863,0.165339,0.380147,-0.116959,0.017475,0.058421,0.190790,0.022002
chlorides,0.107889,0.056336,0.245312,0.070863,1.000000,0.015280,0.208901,-0.277759,0.374784,-0.229917,0.048163,-0.124085
free sulfur dioxide,-0.164831,-0.001962,-0.057589,0.165339,0.015280,1.000000,-0.054150,0.072804,0.034445,-0.047095,0.661093,-0.063260
density,0.681501,0.016512,0.375243,0.380147,0.208901,-0.054150,1.000000,-0.352775,0.143139,-0.494727,0.050175,-0.175208
pH,-0.685163,0.221492,-0.546339,-0.116959,-0.277759,0.072804,-0.352775,1.000000,-0.185499,0.225322,-0.059126,-0.052453
sulphates,0.174592,-0.276079,0.331232,0.017475,0.374784,0.034445,0.143139,-0.185499,1.000000,0.094421,0.026894,0.257710
alcohol,-0.075055,-0.203909,0.106250,0.058421,-0.229917,-0.047095,-0.494727,0.225322,0.094421,1.000000,-0.188165,0.484866
total sulfur dioxide,-0.110628,0.077748,0.036871,0.190790,0.048163,0.661093,0.050175,-0.059126,0.026894,-0.188165,1.000000,-0.183339
quality,0.121970,-0.407394,0.240821,0.022002,-0.124085,-0.063260,-0.175208,-0.052453,0.257710,0.484866,-0.183339,1.000000

In [42]:
x=data.drop(['quality','quality_label'],axis=1)

In [44]:
y=data['quality_label']

In [45]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=42)

In [47]:
model2=RandomForestClassifier()
model2.fit(xtrain,ytrain)

RandomForestClassifier()

In [48]:
output2=model2.predict(xtest)
output2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0])

In [49]:
accuracy2=accuracy_score(ytest,output2)
accuracy2=accuracy2*100
print(accuracy2)

92.13973799126637

In [51]:
scaler = StandardScaler()

X_train = scaler.fit_transform(xtrain)
X_test = scaler.transform(xtest)

In [ ]:
# Taking user input
fixed_acidity = float(input("Enter fixed acidity: "))
volatile_acidity = float(input("Enter volatile acidity: "))
citric_acid = float(input("Enter citric acid: "))
residual_sugar = float(input("Enter residual sugar: "))
chlorides = float(input("Enter chlorides: "))
free_sulfur_dioxide = float(input("Enter free sulfur dioxide: "))
density = float(input("Enter density: "))
pH = float(input("Enter pH: "))
sulphates = float(input("Enter sulphates: "))
alcohol = float(input("Enter alcohol: "))
total_sulfur_dioxide = float(input("Enter total sulfur dioxide: "))

input_data = [[fixed_acidity, volatile_acidity, citric_acid,
               residual_sugar, chlorides, free_sulfur_dioxide,
               density, pH, sulphates, alcohol,
               total_sulfur_dioxide]]

input_data_scaled = scaler.transform(input_data)

# Predict
prediction = model2.predict(input_data_scaled)

print("Prediction:", prediction)